### ISSUE TITLE
When doing VectorToRaster(...) - ValueError: FeatureType.MASK feature has to be <class 'numpy.ndarray'> of dimension 4

### ISSUE THREAD

**Issue by kvigulis** [sentinel-hub/eo-learn#11]
Hi,
I'm trying to generate my own masks for the patches that go through a workflow using a geojson file. 

This is the task that I'm trying to execute:
> vec_to_raster = VectorToRaster((FeatureType.MASK, 'REGION'), region_geojson, 1, (1000, 1000))

The vector data - `region_geojson` is a polygon that I used to generate the splits for patches. It should either totally encompass or intersect a patch.

When I try to run it I get this error: 
```Traceback (most recent call last):
  File "/home/karlis/PythonProjects/sentinel_mining/L1C_patches.py", line 151, in <module>
    save: {'eopatch_folder': patch_name}
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eoworkflow.py", line 165, in execute
    _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eoworkflow.py", line 188, in _execute_tasks
    monitor=monitor)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eoworkflow.py", line 215, in _execute_task
    return task(*inputs, **kw_inputs, monitor=monitor)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eotask.py", line 49, in __call__
    return self.execute(*eopatches, **kwargs)
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/geometry/utilities.py", line 86, in execute
    eopatch[self.feature_type][self.feature_name] = raster[..., np.newaxis]
  File "/home/karlis/PythonProjects/sentinel_mining/venv/lib/python3.6/site-packages/eolearn/core/eodata.py", line 653, in __setitem__
    raise ValueError('{} feature has to be {} of dimension {}'.format(self.feature_type, np.ndarray, self.ndim))
ValueError: FeatureType.MASK feature has to be <class 'numpy.ndarray'> of dimension 4
```
Am I doing something wrong or it could be a bug?

Thanks a lot :)

**Comment by devisperessutti** [comment]
Hi,

Can you please try `(FeatureType.MASK_TIMELESS, 'REGION')` instead of `(FeatureType.MASK, 'REGION')`?

The output raster should be a timeless feature of dimension 3, instead of a time-dependent mask of dimension 4.

**Comment by mlubej** [comment]
@kvigulis has this been resolved?

**Comment by kvigulis** [comment]
Hi, Sorry for the late response. Yes, this solved the issue, thanks very much :)
