### ISSUE TITLE
Land-cover-map example: ValueError when running SimpleFilterTask

### ISSUE THREAD

**Issue by esbenpalmstrom** [sentinel-hub/eo-learn#90]
Hi
I've been trying to rework your land-cover-map in order to make a classification of another region, which means I'm using another shape for the region and another reference map.
When i get to part 2, where I have to use the SimpleFilterTask, i get this error:

```
Traceback (most recent call last):

  File "<ipython-input-13-b40e61641a96>", line 8, in <module>
    workflow.execute(extra_param)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eoworkflow.py", line 167, in execute
    _, intermediate_results = self._execute_tasks(input_args=input_args, out_degs=out_degs, monitor=monitor)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eoworkflow.py", line 206, in _execute_tasks
    monitor=monitor)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eoworkflow.py", line 239, in _execute_task
    return task(*inputs, **kw_inputs, monitor=monitor)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eotask.py", line 52, in __call__
    return self._execute_handling(*eopatches, **kwargs)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eotask.py", line 73, in _execute_handling
    exception)).with_traceback(traceback)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eotask.py", line 66, in _execute_handling
    return_value = self.execute(*eopatches, **kwargs)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/features/feature_manipulation.py", line 61, in execute
    idx in good_idxs])

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eodata.py", line 787, in __setitem__
    value = self._parse_feature_value(value)

  File "/opt/anaconda3/lib/python3.7/site-packages/eolearn/core/eodata.py", line 819, in _parse_feature_value
    'dimension{}'.format(self.feature_type, self.ndim, 's' if self.ndim > 1 else ''))

ValueError: During execution of task SimpleFilterTask: Numpy array of FeatureType.DATA feature has to have 4 dimensions
```
I run the same workflow as in the example.

I don't understand the error since it appears to me that the arrays have the correct dimensions.
When i run `EOPatch.load` i get the following:
```
EOPatch(
  data: {
    BANDS: numpy.ndarray(shape=(60, 1004, 998, 6), dtype=float32)
    CLP: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=float32)
    NDVI: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=float32)
    NDWI: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=float32)
    NORM: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=float32)
  }
  mask: {
    CLM: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=bool)
    IS_DATA: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=bool)
    IS_VALID: numpy.ndarray(shape=(60, 1004, 998, 1), dtype=bool)
  }
  scalar: {}
  label: {}
  vector: {}
  data_timeless: {}
  mask_timeless: {
    LULC: numpy.ndarray(shape=(1005, 999, 1), dtype=uint8)
    VALID_COUNT: numpy.ndarray(shape=(1004, 998, 1), dtype=int64)
  }
  scalar_timeless: {}
  label_timeless: {}
  vector_timeless: {}
  meta_info: {
    maxcc: 0.8
    service_type: 'wcs'
    size_x: '10m'
    size_y: '10m'
    time_difference: datetime.timedelta(days=-1, seconds=86399)
    time_interval: ['2017-01-01', '2017-12-31']
  }
  bbox: BBox(((582613.2881555471, 6351934.719896286), (592595.572278152, 6361973.034025557)), crs=EPSG:32632)
  timestamp: [datetime.datetime(2017, 1, 3, 10, 44, 28), ..., datetime.datetime(2017, 12, 29, 10, 44, 34)], length=60
)
```

**Comment by azupanc** [comment]
Is it possible that SimpleFilterTask removes all time frames in your case?

**Comment by esbenpalmstrom** [comment]
It turned out that my mask arrays were filled with instances of False, so yes.
I tried downloading the data for a couple of different time intervals, but it still didn't work. 
When i switched to another machine and ran the exact same script it worked..

**Comment by azupanc** [comment]
Strange. Perhaps you can run tests provided with the s2cloudless in order to confirm that cloud detection works as it should.
